//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
// TEXCOORD                 3   xyzw        4     NONE   float   xyzw
// COLOR                    0   xyzw        5     NONE   float    yz 
// TEXCOORD                 6   xyzw        6     NONE   float       
// TEXCOORD                 7   xyzw        7     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_4_0
dcl_constantbuffer CB0[27], immediateIndexed
dcl_constantbuffer CB1[5], immediateIndexed
dcl_constantbuffer CB2[47], immediateIndexed
dcl_constantbuffer CB3[8], immediateIndexed
dcl_constantbuffer CB4[7], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s3, mode_default
dcl_sampler s4, mode_default
dcl_sampler s5, mode_default
dcl_sampler s6, mode_default
dcl_sampler s7, mode_default
dcl_sampler s8, mode_default
dcl_sampler s9, mode_default
dcl_sampler s10, mode_default
dcl_sampler s11, mode_default
dcl_sampler s12, mode_default
dcl_sampler s13, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t4
dcl_resource_texture2d (float,float,float,float) t5
dcl_resource_texture2d (float,float,float,float) t6
dcl_resource_texture2d (float,float,float,float) t7
dcl_resource_texture2d (float,float,float,float) t8
dcl_resource_texture2d (float,float,float,float) t9
dcl_resource_texture2d (float,float,float,float) t10
dcl_resource_texture2d (float,float,float,float) t11
dcl_resource_texturecube (float,float,float,float) t12
dcl_resource_texturecube (float,float,float,float) t13
dcl_resource_texture3d (float,float,float,float) t14
dcl_input_ps linear v1.xyzw
dcl_input_ps linear v2.xyzw
dcl_input_ps linear v3.xyzw
dcl_input_ps linear v4.xyzw
dcl_input_ps linear v5.yz
dcl_output o0.xyzw
dcl_temps 14
mov r0.x, v2.w
mov r0.y, v3.w
mov r0.z, v4.w
add r1.xyz, -r0.xyzx, cb1[4].xyzx
dp3 r0.w, r1.xyzx, r1.xyzx
rsq r0.w, r0.w
mul r2.xyz, r0.wwww, r1.xyzx
mad r3.xy, v1.xyxx, cb0[5].xyxx, cb0[5].zwzz
sample r4.xyzw, r3.xyxx, t0.xyzw, s3
sample r5.xyzw, v1.xyxx, t1.xyzw, s4
mul r1.w, r5.y, cb0[6].x
mul r1.w, r1.w, cb0[6].y
mul r1.w, r1.w, l(9.000000)
add r3.zw, r3.xxxy, l(0.000000, 0.000000, 0.001563, 0.001563)
sample r6.xyzw, r3.zyzz, t0.xyzw, s3
add r2.w, -r4.y, r6.y
mul r6.x, r1.w, r2.w
sample r3.xyzw, r3.xwxx, t0.xyzw, s3
add r2.w, -r4.y, r3.y
mul r6.y, r1.w, r2.w
mov r6.z, l(0)
add r3.xyz, -r6.xyzx, l(0.000000, 0.000000, 1.000000, 0.000000)
dp3 r1.w, r3.xyzx, r3.xyzx
rsq r1.w, r1.w
mul r3.xyz, r1.wwww, r3.xyzx
mad r4.xz, cb0[6].zzzz, l(-4.200000, 0.000000, -4.200000, 0.000000), l(5.000000, 0.000000, 4.000000, 0.000000)
mul r1.w, r4.z, l(-0.500000)
mad r4.xz, v1.zzwz, r4.xxxx, r1.wwww
add r6.xy, v1.zwzz, l(-0.500000, -0.500000, 0.000000, 0.000000)
dp2 r1.w, r6.xyxx, r6.xyxx
sqrt r1.w, r1.w
mad r1.w, r1.w, l(-4.000000), l(1.000000)
max r1.w, r1.w, l(0.000000)
add r6.xy, -r4.xzxx, v1.zwzz
mad_sat r6.xy, r1.wwww, r6.xyxx, r4.xzxx
sample r7.xyzw, r6.xyxx, t2.xyzw, s5
add r4.xz, -v5.yyzy, l(1.000000, 0.000000, 1.000000, 0.000000)
mul r1.w, cb0[7].w, l(8.000000)
mul r1.w, r4.x, r1.w
add r6.zw, r6.xxxy, l(0.000000, 0.000000, 0.001563, 0.001563)
sample r8.xyzw, r6.zyzz, t2.xyzw, s5
add r2.w, -r7.y, r8.y
mul r8.x, r1.w, r2.w
sample r6.xyzw, r6.xwxx, t2.xyzw, s5
add r2.w, -r7.y, r6.y
mul r8.y, r1.w, r2.w
mov r8.z, l(0)
add r6.xyz, -r8.xyzx, l(0.000000, 0.000000, 1.000000, 0.000000)
dp3 r1.w, r6.xyzx, r6.xyzx
rsq r1.w, r1.w
mul r6.xyz, r1.wwww, r6.xyzx
mul r1.w, cb0[9].x, l(3.141593)
sincos r8.x, r9.x, r1.w
add r7.yw, v1.zzzw, cb0[8].xxxy
add r7.yw, r7.yyyw, l(0.000000, -0.300000, 0.000000, -0.400000)
mov r10.x, -r8.x
mov r10.y, r9.x
mov r10.z, r8.x
dp2 r8.x, r7.ywyy, r10.yzyy
dp2 r8.y, r7.ywyy, r10.xyxx
add r7.yw, r8.xxxy, l(0.000000, 0.300000, 0.000000, 0.400000)
add r8.xy, cb0[8].zwzz, l(-1.000000, -1.000000, 0.000000, 0.000000)
mul r8.xy, r8.xyxx, l(-0.100000, -0.430000, 0.000000, 0.000000)
mad r8.xy, r7.ywyy, cb0[8].zwzz, r8.xyxx
sample r9.xyzw, r8.xyxx, t3.xyzw, s6
add r8.zw, r8.xxxy, l(0.000000, 0.000000, 0.005487, 0.005487)
sample r10.xyzw, r8.zyzz, t3.xyzw, s6
add r1.w, -r9.y, r10.y
mul r10.x, r4.z, r1.w
sample r8.xyzw, r8.xwxx, t3.xyzw, s6
add r1.w, -r9.y, r8.y
mul r10.y, r4.z, r1.w
mov r10.z, l(0)
add r8.xyz, -r10.xyzx, l(0.000000, 0.000000, 1.000000, 0.000000)
dp3 r1.w, r8.xyzx, r8.xyzx
rsq r1.w, r1.w
mul r8.xyz, r1.wwww, r8.xyzx
mad r10.yz, v1.xxyx, cb0[10].xxyx, cb0[10].zzwz
add r1.w, -r10.y, l(0.500000)
mov r10.x, |r1.w|
sample r11.xyzw, r10.xzxx, t4.xyzw, s7
mul r1.w, cb0[11].w, l(1.500000)
add r10.w, r10.x, l(0.005487)
sample r12.xyzw, r10.wzww, t4.xyzw, s7
add r2.w, -r11.y, r12.y
mul r12.x, r1.w, r2.w
add r7.yw, r10.xxxz, l(0.000000, 0.000000, 0.000000, 0.005487)
sample r10.xyzw, r7.ywyy, t4.xyzw, s7
add r2.w, -r11.y, r10.y
mul r12.y, r1.w, r2.w
mov r12.z, l(0)
add r9.xyw, -r12.xyxz, l(0.000000, 0.000000, 0.000000, 1.000000)
dp3 r1.w, r9.xywx, r9.xywx
rsq r1.w, r1.w
mul r9.xyw, r1.wwww, r9.xyxw
sample r10.xyzw, v1.xyxx, t5.xyzw, s2
mul r10.x, r10.w, r10.x
mad r7.yw, r10.xxxy, l(0.000000, 2.000000, 0.000000, 2.000000), l(0.000000, -1.000000, 0.000000, -1.000000)
mul r10.xy, r7.ywyy, cb0[4].xxxx
dp2 r1.w, r10.xyxx, r10.xyxx
min r1.w, r1.w, l(1.000000)
add r1.w, -r1.w, l(1.000000)
sqrt r1.w, r1.w
mad r10.xy, r7.ywyy, cb0[4].xxxx, r3.xyxx
mul r10.z, r3.z, r1.w
dp3 r1.w, r10.xyzx, r10.xyzx
rsq r1.w, r1.w
mul r2.w, r1.w, r10.z
mad r3.xy, r10.xyxx, r1.wwww, r6.xyxx
mul r3.z, r6.z, r2.w
dp3 r1.w, r3.xyzx, r3.xyzx
rsq r1.w, r1.w
mul r2.w, r1.w, r3.z
mad r3.xy, r3.xyxx, r1.wwww, r8.xyxx
mul r3.z, r8.z, r2.w
dp3 r1.w, r3.xyzx, r3.xyzx
rsq r1.w, r1.w
mul r2.w, r1.w, r3.z
mad r3.xy, r3.xyxx, r1.wwww, r9.xyxx
mul r3.z, r9.w, r2.w
dp3 r1.w, r3.xyzx, r3.xyzx
rsq r1.w, r1.w
mul r2.w, r1.w, r3.z
mad r3.zw, v1.xxxy, cb0[13].xxxy, cb0[13].zzzw
sample r6.xyzw, v1.xyxx, t6.xyzw, s10
add r6.w, -r6.w, l(1.000000)
mul r6.w, r6.w, l(3.141593)
sincos r8.x, r9.x, r6.w
mov r10.x, -r8.x
mov r10.y, r9.x
mov r10.z, r8.x
dp2 r8.x, r3.zwzz, r10.yzyy
dp2 r8.y, r3.zwzz, r10.xyxx
sample r10.xyzw, r8.xyxx, t7.xyzw, s9
max r9.xyw, r6.yzyz, r6.xxxy
add_sat r11.yzw, r6.xxyz, -r9.wwyx
add_sat r6.xyz, -r6.zyxz, r9.xywx
add r3.z, r11.z, r11.y
add r3.z, r11.w, r3.z
add r6.xyz, -r3.zzzz, r6.xyzx
max r6.xyz, r6.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
min r9.xyw, r11.yzyw, cb0[14].xyxz
add r3.z, r9.y, r9.x
add r3.z, r9.w, r3.z
min r3.w, r6.x, cb0[14].w
add r3.z, r3.w, r3.z
min r6.xy, r6.yzyy, cb0[15].xyxx
add r3.z, r3.z, r6.x
add r3.z, r6.y, r3.z
add_sat r3.z, r3.z, cb0[15].z
lt r3.w, l(0.500000), r3.z
add r6.x, r3.z, l(-0.500000)
add r6.x, r6.x, r6.x
min r6.x, r10.x, r6.x
max r6.x, r10.z, r6.x
eq r6.y, r3.z, l(0.500000)
lt r6.z, r3.z, l(0.500000)
add r6.w, r3.z, r3.z
min r6.w, r10.z, r6.w
and r6.z, r6.w, r6.z
movc r6.y, r6.y, r10.z, r6.z
movc r3.w, r3.w, r6.x, r6.y
mul r6.xy, r3.wwww, l(6.000000, 0.150000, 0.000000, 0.000000)
add r8.zw, r8.xxxy, l(0.000000, 0.000000, 0.009112, 0.009112)
sample r12.xyzw, r8.zyzz, t7.xyzw, s9
add r6.z, -r10.y, r12.y
mul r12.x, r6.x, r6.z
sample r8.xyzw, r8.xwxx, t7.xyzw, s9
add r6.z, -r10.y, r8.y
mul r12.y, r6.x, r6.z
mov r12.z, l(0)
add r6.xzw, -r12.xxyz, l(0.000000, 0.000000, 0.000000, 1.000000)
dp3 r7.y, r6.xzwx, r6.xzwx
rsq r7.y, r7.y
min r3.z, r3.w, r3.z
sample r8.xyzw, v1.xyxx, t8.xyzw, s8
mul r8.x, r8.w, r8.x
mad r8.xy, r8.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
mul r8.xy, r8.xyxx, cb0[12].xxxx
dp2 r7.w, r8.xyxx, r8.xyxx
min r7.w, r7.w, l(1.000000)
add r7.w, -r7.w, l(1.000000)
sqrt r7.w, r7.w
mad r8.xy, r3.xyxx, r1.wwww, r8.xyxx
mul r8.z, r2.w, r7.w
dp3 r1.w, r8.xyzx, r8.xyzx
rsq r1.w, r1.w
mul r8.xyz, r1.wwww, r8.xyzx
mad r6.xzw, r6.xxzw, r7.yyyy, -r8.xxyz
mad r6.xzw, r3.zzzz, r6.xxzw, r8.xxyz
mul r1.w, r5.x, cb0[17].w
add r8.xyz, -cb0[16].xyzx, cb0[17].xyzx
mad r8.xyz, r1.wwww, r8.xyzx, cb0[16].xyzx
sample r10.xyzw, v1.xyxx, t9.xyzw, s11
mul r9.xyw, r8.xyxz, r10.xyxz
mul r1.w, r5.z, cb0[19].x
mul r1.w, r1.w, cb0[18].w
mad r8.xyz, -r10.xyzx, r8.xyzx, cb0[18].xyzx
mad r8.xyz, r1.wwww, r8.xyzx, r9.xywx
ge r1.w, r8.y, r8.z
and r1.w, r1.w, l(0x3f800000)
mov r10.xy, r8.zyzz
mov r10.zw, l(0,0,-1.000000,0.666667)
add r12.xy, r8.yzyy, -r10.xyxx
mov r12.zw, l(0,0,1.000000,-1.000000)
mad r10.xyzw, r1.wwww, r12.xyzw, r10.xyzw
ge r1.w, r8.x, r10.x
and r1.w, r1.w, l(0x3f800000)
mov r12.xyz, r10.xywx
mov r12.w, r8.x
mov r10.xyw, r12.wywx
add r10.xyzw, -r12.xyzw, r10.xyzw
mad r10.xyzw, r1.wwww, r10.xyzw, r12.xyzw
min r1.w, r10.y, r10.w
add r1.w, -r1.w, r10.x
add r2.w, -r10.y, r10.w
mad r3.x, r1.w, l(6.000000), l(0.000000)
div r2.w, r2.w, r3.x
add r2.w, r2.w, r10.z
add r3.x, r10.x, l(0.000000)
div r1.w, r1.w, r3.x
add r9.xyw, |r2.wwww|, l(1.000000, 0.666667, 0.000000, 0.333333)
frc r9.xyw, r9.xyxw
mad r9.xyw, r9.xyxw, l(6.000000, 6.000000, 0.000000, 6.000000), l(-3.000000, -3.000000, 0.000000, -3.000000)
add_sat r9.xyw, |r9.xyxw|, l(-1.000000, -1.000000, 0.000000, -1.000000)
add r9.xyw, r9.xyxw, l(-1.000000, -1.000000, 0.000000, -1.000000)
mad r9.xyw, r1.wwww, r9.xyxw, l(1.000000, 1.000000, 0.000000, 1.000000)
mul r9.xyw, r9.xyxw, l(0.800000, 0.800000, 0.000000, 0.800000)
sample r10.xyzw, v1.xyxx, t10.xyzw, s12
mul r1.w, r10.z, cb0[12].x
mul r2.w, r1.w, l(0.150000)
mad r9.xyw, r8.xyxz, r9.xyxw, -r8.xyxz
mad r8.xyw, r2.wwww, r9.ywyx, r8.yzyx
mul r2.w, r9.z, cb0[20].w
mul r3.x, r4.z, r2.w
mad r9.xyz, r9.zzzz, cb0[20].xyzx, -r8.wxyw
mad r9.xyz, r3.xxxx, r9.xyzx, r8.wxyw
mul r7.xyzw, r7.zxxx, cb0[7].wxyz
mul r3.y, r4.x, r7.x
mad r7.xyz, r7.yzwy, l(0.700000, 0.700000, 0.700000, 0.000000), -r9.xyzx
mad r7.xyz, r3.yyyy, r7.xyzx, r9.xyzx
add_sat r4.x, cb0[11].w, cb0[11].w
mad r5.z, cb0[11].w, l(-3.000000), l(4.000000)
log r7.w, r11.x
mul r5.z, r5.z, r7.w
exp r5.z, r5.z
mul r4.x, r4.x, r5.z
add r9.xyz, -r7.xyzx, cb0[11].xyzx
mad r7.xyz, r4.xxxx, r9.xyzx, r7.xyzx
add r9.xyz, -r7.xyzx, l(0.699000, 0.699000, 0.699000, 0.000000)
mad r7.xyz, r6.yyyy, r9.xyzx, r7.xyzx
dp3 r9.x, v2.xyzx, r6.xzwx
dp3 r9.y, v3.xyzx, r6.xzwx
dp3 r9.z, v4.xyzx, r6.xzwx
dp3 r5.z, r9.xyzx, r2.xyzx
add r5.z, -r5.z, l(1.000000)
log r5.z, r5.z
mul r5.z, r5.z, cb0[21].z
exp r5.z, r5.z
mad_sat r5.z, cb0[21].y, r5.z, cb0[21].x
mul r3.y, r3.y, cb0[22].x
mul r6.xy, r10.xxxx, cb0[22].ywyy
add r6.z, -r5.y, l(1.000000)
max r4.yw, r4.wwwy, r6.zzzz
mul r4.y, r4.y, r6.x
max r3.y, r3.y, r4.y
mad r2.w, -r2.w, r4.z, l(1.000000)
min r2.w, r2.w, r3.y
mad r2.w, r3.x, l(0.150000), r2.w
min r3.x, r5.x, cb0[22].z
add_sat r2.w, r2.w, r3.x
mul r3.x, r4.x, l(0.500000)
max r2.w, r2.w, r3.x
max r2.w, r6.y, r2.w
mad r3.xy, v1.xyxx, cb0[23].xyxx, cb0[23].zwzz
sample r6.xyzw, r3.xyxx, t11.xyzw, s13
dp3 r3.x, cb2[0].xyzx, cb2[0].xyzx
rsq r3.x, r3.x
mul r4.xyz, r3.xxxx, cb2[0].xyzx
dp3_sat r3.x, r4.xyzx, r9.xyzx
add r3.y, -r5.z, l(1.000000)
mul r4.xy, r6.zxzz, cb0[24].xxxx
max r2.w, r2.w, r4.x
add r2.w, r3.z, r2.w
mul r3.y, r2.w, r3.y
mul r3.y, r3.y, cb0[21].w
mul r3.x, r3.x, r3.y
mad_sat r3.xyz, r3.xxxx, r5.yyyy, r7.xyzx
max r4.x, r4.y, cb0[24].y
mad r3.w, -r3.w, l(0.150000), l(1.000000)
min r3.w, r3.w, r4.x
add r4.x, -cb0[24].z, l(1.000000)
min r4.y, r4.w, r10.y
mad r4.y, -r1.w, l(0.080000), r4.y
add r4.z, -r4.x, l(1.000000)
mad r4.x, r4.y, r4.z, r4.x
ge r4.y, r8.x, r8.y
and r4.y, r4.y, l(0x3f800000)
mov r6.xy, r8.yxyy
mov r6.zw, l(0,0,-1.000000,0.666667)
add r7.xy, -r6.xyxx, r8.xyxx
mov r7.zw, l(0,0,1.000000,-1.000000)
mad r6.xyzw, r4.yyyy, r7.xyzw, r6.xyzw
ge r4.y, r8.w, r6.x
and r4.y, r4.y, l(0x3f800000)
mov r8.xyz, r6.xywx
mov r6.xyw, r8.wywx
add r6.xyzw, -r8.xyzw, r6.xyzw
mad r6.xyzw, r4.yyyy, r6.xyzw, r8.xyzw
min r4.y, r6.y, r6.w
add r4.y, -r4.y, r6.x
add r4.z, -r6.y, r6.w
mad r4.w, r4.y, l(6.000000), l(0.000000)
div r4.z, r4.z, r4.w
add r4.z, r4.z, r6.z
add r4.w, r6.x, l(0.000000)
div r4.y, r4.y, r4.w
ge r4.w, l(0.000000), r6.x
mad r1.w, r1.w, l(0.150000), r6.x
add r5.xyz, |r4.zzzz|, l(1.000000, 0.666667, 0.333333, 0.000000)
frc r5.xyz, r5.xyzx
mad r5.xyz, r5.xyzx, l(6.000000, 6.000000, 6.000000, 0.000000), l(-3.000000, -3.000000, -3.000000, 0.000000)
add_sat r5.xyz, |r5.xyzx|, l(-1.000000, -1.000000, -1.000000, 0.000000)
add r5.xyz, r5.xyzx, l(-1.000000, -1.000000, -1.000000, 0.000000)
movc r5.xyz, r4.wwww, l(0,-1.000000,-1.000000,0), r5.xyzx
mad r4.yzw, r4.yyyy, r5.xxyz, l(0.000000, 1.000000, 1.000000, 1.000000)
mul r4.yzw, r1.wwww, r4.yyzw
mul r4.yzw, r5.wwww, r4.yyzw
eq r1.w, cb4[0].x, l(1.000000)
if_nz r1.w
  eq r1.w, cb4[0].y, l(1.000000)
  mul r5.xyz, v3.wwww, cb4[2].xyzx
  mad r5.xyz, cb4[1].xyzx, v2.wwww, r5.xyzx
  mad r5.xyz, cb4[3].xyzx, v4.wwww, r5.xyzx
  add r5.xyz, r5.xyzx, cb4[4].xyzx
  movc r5.xyz, r1.wwww, r5.xyzx, r0.xyzx
  add r5.xyz, r5.xyzx, -cb4[6].xyzx
  mul r5.yzw, r5.xxyz, cb4[5].xxyz
  mad r1.w, r5.y, l(0.250000), l(0.750000)
  mad r5.y, cb4[0].z, l(0.500000), l(0.750000)
  max r5.x, r1.w, r5.y
  sample r5.xyzw, r5.xzwx, t14.xyzw, s1
else 
  mov r5.xyzw, l(1.000000,1.000000,1.000000,1.000000)
endif 
dp4_sat r1.w, r5.xyzw, cb2[46].xyzw
dp3 r5.x, r9.xyzx, r9.xyzx
rsq r5.x, r5.x
mul r5.xyz, r5.xxxx, r9.xyzx
add r5.w, -r2.w, l(1.000000)
dp3 r6.x, -r2.xyzx, r5.xyzx
add r6.x, r6.x, r6.x
mad r6.xyz, r5.xyzx, -r6.xxxx, -r2.xyzx
mul r7.xyz, r1.wwww, cb0[2].xyzx
lt r6.w, l(0.000000), cb3[2].w
if_nz r6.w
  dp3 r6.w, r6.xyzx, r6.xyzx
  rsq r6.w, r6.w
  mul r8.xyz, r6.wwww, r6.xyzx
  add r9.xyz, -r0.xyzx, cb3[0].xyzx
  div r9.xyz, r9.xyzx, r8.xyzx
  add r10.xyz, -r0.xyzx, cb3[1].xyzx
  div r10.xyz, r10.xyzx, r8.xyzx
  lt r11.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r8.xyzx
  movc r9.xyz, r11.xyzx, r9.xyzx, r10.xyzx
  min r6.w, r9.y, r9.x
  min r6.w, r9.z, r6.w
  add r9.xyz, r0.xyzx, -cb3[2].xyzx
  mad r8.xyz, r8.xyzx, r6.wwww, r9.xyzx
else 
  mov r8.xyz, r6.xyzx
endif 
mad r6.w, -r5.w, l(0.700000), l(1.700000)
mul r6.w, r5.w, r6.w
mul r6.w, r6.w, l(6.000000)
sample_l r8.xyzw, r8.xyzx, t12.xyzw, s0, r6.w
add r7.w, r8.w, l(-1.000000)
mad r7.w, cb3[3].w, r7.w, l(1.000000)
log r7.w, r7.w
mul r7.w, r7.w, cb3[3].y
exp r7.w, r7.w
mul r7.w, r7.w, cb3[3].x
mul r9.xyz, r8.xyzx, r7.wwww
lt r8.w, cb3[1].w, l(0.999990)
if_nz r8.w
  lt r8.w, l(0.000000), cb3[6].w
  if_nz r8.w
    dp3 r8.w, r6.xyzx, r6.xyzx
    rsq r8.w, r8.w
    mul r10.xyz, r6.xyzx, r8.wwww
    add r11.xyz, -r0.xyzx, cb3[4].xyzx
    div r11.xyz, r11.xyzx, r10.xyzx
    add r12.xyz, -r0.xyzx, cb3[5].xyzx
    div r12.xyz, r12.xyzx, r10.xyzx
    lt r13.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r10.xyzx
    movc r11.xyz, r13.xyzx, r11.xyzx, r12.xyzx
    min r8.w, r11.y, r11.x
    min r8.w, r11.z, r8.w
    add r0.xyz, r0.xyzx, -cb3[6].xyzx
    mad r6.xyz, r10.xyzx, r8.wwww, r0.xyzx
  endif 
  sample_l r6.xyzw, r6.xyzx, t13.xyzw, s0, r6.w
  add r0.x, r6.w, l(-1.000000)
  mad r0.x, cb3[7].w, r0.x, l(1.000000)
  log r0.x, r0.x
  mul r0.x, r0.x, cb3[7].y
  exp r0.x, r0.x
  mul r0.x, r0.x, cb3[7].x
  mul r0.xyz, r6.xyzx, r0.xxxx
  mad r6.xyz, r7.wwww, r8.xyzx, -r0.xyzx
  mad r9.xyz, cb3[1].wwww, r6.xyzx, r0.xyzx
endif 
mul r0.xyz, r4.xxxx, r9.xyzx
mad r6.xyz, cb0[2].xyzx, r1.wwww, -cb0[2].xyzx
mad r6.xyz, cb0[26].xxxx, r6.xyzx, cb0[2].xyzx
mad r8.xyz, r5.xyzx, cb0[25].xxxx, cb2[0].xyzx
dp3_sat r1.w, r2.xyzx, -r8.xyzx
log r1.w, r1.w
mul r1.w, r1.w, cb0[25].y
exp r1.w, r1.w
mul r1.w, r1.w, cb0[25].z
mul r6.xyz, r1.wwww, r6.xyzx
mul r4.xyz, r4.yzwy, r6.xyzx
mul r4.xyz, r3.xyzx, r4.xyzx
add r6.xyz, r3.xyzx, l(-0.040000, -0.040000, -0.040000, 0.000000)
mad r6.xyz, r3.wwww, r6.xyzx, l(0.040000, 0.040000, 0.040000, 0.000000)
mad r1.w, -r3.w, l(0.960000), l(0.960000)
mul r3.xyz, r1.wwww, r3.xyzx
mad r1.xyz, r1.xyzx, r0.wwww, cb2[0].xyzx
dp3 r0.w, r1.xyzx, r1.xyzx
max r0.w, r0.w, l(0.001000)
rsq r0.w, r0.w
mul r1.xyz, r0.wwww, r1.xyzx
dp3 r0.w, r5.xyzx, r2.xyzx
dp3_sat r2.x, r5.xyzx, cb2[0].xyzx
dp3_sat r2.y, r5.xyzx, r1.xyzx
dp3_sat r1.x, cb2[0].xyzx, r1.xyzx
mul r1.y, r1.x, r1.x
dp2 r1.y, r1.yyyy, r5.wwww
add r1.y, r1.y, l(-0.500000)
add r1.z, -r2.x, l(1.000000)
mul r2.z, r1.z, r1.z
mul r2.z, r2.z, r2.z
mul r1.z, r1.z, r2.z
mad r1.z, r1.y, r1.z, l(1.000000)
add r2.z, -|r0.w|, l(1.000000)
mul r3.w, r2.z, r2.z
mul r3.w, r3.w, r3.w
mul r2.z, r2.z, r3.w
mad r1.y, r1.y, r2.z, l(1.000000)
mul r1.y, r1.y, r1.z
mul r1.y, r2.x, r1.y
mul r1.z, r5.w, r5.w
max r1.z, r1.z, l(0.002000)
add r3.w, -r1.z, l(1.000000)
mad r4.w, |r0.w|, r3.w, r1.z
mad r3.w, r2.x, r3.w, r1.z
mul r0.w, |r0.w|, r3.w
mad r0.w, r2.x, r4.w, r0.w
add r0.w, r0.w, l(0.000010)
div r0.w, l(0.500000), r0.w
mul r3.w, r1.z, r1.z
mad r4.w, r2.y, r3.w, -r2.y
mad r2.y, r4.w, r2.y, l(1.000000)
mul r3.w, r3.w, l(0.318310)
mad r2.y, r2.y, r2.y, l(0.000000)
div r2.y, r3.w, r2.y
mul r0.w, r0.w, r2.y
mul r0.w, r0.w, l(3.141593)
mul r0.w, r2.x, r0.w
max r0.w, r0.w, l(0.000000)
mad r1.z, r1.z, r1.z, l(1.000000)
div r1.z, l(1.000000, 1.000000, 1.000000, 1.000000), r1.z
dp3 r2.x, r6.xyzx, r6.xyzx
ne r2.x, r2.x, l(0.000000)
and r2.x, r2.x, l(0x3f800000)
mul r0.w, r0.w, r2.x
add r1.w, -r1.w, l(1.000000)
add_sat r1.w, r1.w, r2.w
mul r2.xyw, r1.yyyy, r7.xyxz
mul r5.xyz, r7.xyzx, r0.wwww
add r0.w, -r1.x, l(1.000000)
mul r1.x, r0.w, r0.w
mul r1.x, r1.x, r1.x
mul r0.xyzw, r0.xyzw, r1.zzzx
add r7.xyz, -r6.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
mad r7.xyz, r7.xyzx, r0.wwww, r6.xyzx
mul r5.xyz, r5.xyzx, r7.xyzx
mad r2.xyw, r3.xyxz, r2.xyxw, r5.xyxz
add r1.xyz, -r6.xyzx, r1.wwww
mad r1.xyz, r2.zzzz, r1.xyzx, r6.xyzx
mad r0.xyz, r0.xyzx, r1.xyzx, r2.xywx
mad o0.xyz, r4.xyzx, cb0[24].wwww, r0.xyzx
mov o0.w, l(1.000000)
ret 
// Approximately 0 instruction slots used
